TOOLS = [
    ("video-cutter", "Video cutter", "Media"),
    ("video-merger", "Video merger", "Media"),
    ("audio-extractor", "Audio extractor", "Media"),
    ("subtitle-generator", "Subtitle generator", "Media"),
    ("thumbnail-resizer", "Thumbnail resizer", "Media"),
    ("image-compressor", "Image compressor", "Media"),
    ("background-remover", "Background remover", "Media"),
    ("watermark-tool", "Watermark tool", "Media"),
    ("image-format-converter", "Image format converter", "Media"),
    ("caption-generator", "Caption generator", "Creator"),
    ("hashtag-generator", "Hashtag generator", "Creator"),
    ("content-calendar", "Content calendar", "Creator"),
    ("bio-generator", "Bio generator", "Creator"),
    ("link-in-bio-builder", "Link in bio builder", "Creator"),
    ("reply-template-manager", "Reply template manager", "Creator"),
    ("engagement-tracker", "Engagement tracker", "Creator"),
    ("content-idea-scheduler", "Content idea scheduler", "Creator"),
    ("title-generator", "Title generator", "Creator"),
    ("keyword-clustering", "Keyword clustering", "Creator"),
    ("trend-notes-board", "Trend notes board", "Creator"),
    ("json-formatter", "JSON formatter", "Developer"),
    ("jwt-decoder", "JWT decoder", "Developer"),
    ("base64-encoder-decoder", "Base64 encoder/decoder", "Developer"),
    ("hash-generator", "Hash generator", "Developer"),
    ("regex-tester", "Regex tester", "Developer"),
    ("uuid-generator", "UUID generator", "Developer"),
    ("timestamp-converter", "Timestamp converter", "Developer"),
    ("color-palette-generator", "Color palette generator", "Developer"),
    ("markdown-previewer", "Markdown previewer", "Developer"),
    ("api-request-tester", "API request tester", "Developer"),
    ("to-do-board", "To-do board", "Productivity"),
    ("notes-snippets-manager", "Notes & snippets manager", "Productivity"),
    ("password-generator", "Password generator", "Productivity"),
    ("qr-code-generator", "QR code generator", "Productivity"),
    ("barcode-generator", "Barcode generator", "Productivity"),
    ("pdf-merge", "PDF merge", "Document"),
    ("pdf-split", "PDF split", "Document"),
    ("ocr-dokumen-ringan", "OCR dokumen ringan", "Document"),
    ("invoice-template-generator", "Invoice template generator", "Document"),
    ("batch-file-renamer", "Batch file renamer", "Document"),
    ("website-uptime-checker", "Website uptime checker", "Monitoring"),
    ("ssl-checker", "SSL checker", "Monitoring"),
    ("dns-lookup", "DNS lookup", "Monitoring"),
    ("internal-asset-port-checker", "Internal asset port checker", "Monitoring"),
    ("web-performance-audit", "Web performance audit", "Monitoring"),
    ("broken-link-checker", "Broken link checker", "Monitoring"),
    ("sitemap-validator", "Sitemap validator", "Monitoring"),
    ("robots-txt-checker", "Robots.txt checker", "Monitoring"),
    ("server-resource-dashboard", "Server resource dashboard", "Monitoring"),
    ("log-viewer-alert-ringan", "Log viewer & alert ringan", "Monitoring"),
]
